title: Carlos Armijo
logo: assets/img/cv_picture_no_glasses-min_square_headshot_smaller.png
description: Estudiante de Ciencia de la Computación
show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal